"""create_orders_table

Revision ID: ad18ea202d0d
Revises: d9ed7e1b6042
Create Date: 2023-11-21 18:50:59.897613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad18ea202d0d"
down_revision: Union[str, None] = "d9ed7e1b6042"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "PUBLISHED", "WIP", "DELETED", "DONE", name="orderstatus"),
            nullable=False,
        ),
        sa.Column("budget", sa.String(), nullable=False),
        sa.Column("description", sa.String(length=2083), nullable=False),
        sa.Column("link", sa.String(length=2083), nullable=True),
        sa.Column("worker_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["customer_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["worker_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    # ### end Alembic commands ###
